### ISSUE TITLE
--headers doesn't support header values containing equals symbol

### ISSUE THREAD

**Issue by ceuk** [microsoftgraph/msgraph-cli#343]
Hi, I was testing out adding arbitrary headers with the `--headers` flag added in 1.0.0 and unfortunately it looks like there doesn't seem to be a way to pass a header value containing `=`

e.g. 

```
mgc users calendar calendar-view list --debug --user-id <Redacted> --start-date-time "$(date --iso-8601=seconds)" --end-date-time "$(date --iso-8601=seconds -d '+1 week')" --headers Prefer="outlook.timezone=GMT"
````

Will result in the header value being truncated at the `=` symbol:

```
      Request:
      
      GET https://graph.microsoft.com/v1.0/users/<Redacted>/calendar/calendarView?startDateTime=2023-09-21T11%3A10%3A44%2B01%3A00&endDateTime=2023-09-28T11%3A10%3A44%2B01%3A00&$top=5&$orderby=start%2FdateTime&$select=subject%2Corganizer%2Cstart%2Cend HTTP/1.1
      Accept: application/json
      Authorization: [PROTECTED]
      FeatureFlag: 00000043
      Cache-Control: no-store, no-cache
      User-Agent: kiota-dotnet/1.1.1
      SdkVersion: graph-cli-1.0/1.0.0, graph-dotnet-core/3.0.11 (featureUsage=0000002B; hostOS=Unix 6.5.3.1; hostArch=X64; runtimeEnvironment=.NET 7.0.11;)
      client-request-id: 8654b7a4-fe03-424d-944b-e0b5b7647ca4
      Prefer: outlook.timezone
```

(You can see the header value on the last line of the debug output above)

I've tried various logical variations of providing the header value e.g.

```
--headers Prefer="outlook.timezone\=GMT"
```
Results in: `Prefer: outlook.timezone\`

```
--headers Prefer="outlook.timezone\\=GMT"
```
Results in: `Prefer: outlook.timezone\\`

```
--headers Prefer="outlook.timezone%3DGMT"
```
Results in: `Prefer: outlook.timezone%3DGMT` (which isn't parsed correctly downstream by the looks of it, so still doesn't work)

I've also tried numerous combinations of quotes, double & single, nested, escaped etc. None of which made a difference
